# Generated by Django 2.0.1 on 2018-01-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accountDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('selfIntroduce', models.CharField(max_length=255, null=True)),
                ('phoneNumber', models.CharField(max_length=11, null=True)),
                ('EmailAccount', models.CharField(max_length=30, null=True)),
                ('wechatAccount', models.CharField(max_length=30, null=True)),
                ('weiboAccount', models.CharField(max_length=30, null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('qqAccount', models.CharField(max_length=30, null=True)),
                ('scores', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(help_text='Example:172.25.0.0', max_length=30, unique=True, verbose_name='IP地址')),
                ('STATE', models.CharField(choices=[('down', '设备已关机'), ('up', '设备开机'), ('avi', '此ip未分配')], max_length=30, verbose_name='当前状态')),
                ('MODEL', models.CharField(blank=True, choices=[('fwq', '普通服务器'), ('gmszx', '高密四子星'), ('ups', 'UPS'), ('ccjd', '存储节点'), ('other', '其他')], max_length=30, verbose_name='型号')),
                ('IDD', models.CharField(blank=True, max_length=30, verbose_name='设备编号')),
                ('USER', models.CharField(blank=True, max_length=30, verbose_name='设备使用者')),
                ('TEL', models.CharField(blank=True, max_length=30, verbose_name='联系方式')),
                ('LOC', models.CharField(blank=True, max_length=30, verbose_name='设备位置')),
                ('NOTE', models.CharField(blank=True, max_length=30, verbose_name='备注')),
                ('TIME', models.DateTimeField(auto_now_add=True)),
                ('IPMI', models.CharField(blank=True, help_text='Example:172.25.0.0', max_length=30, unique=True, verbose_name='IPMI地址')),
            ],
        ),
        migrations.CreateModel(
            name='superuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ZSYH_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_address', models.CharField(default='', max_length=255)),
                ('card_name', models.CharField(max_length=255)),
                ('pic_address', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
