# Generated by Django 2.0.1 on 2018-01-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycreditcard', '0002_auto_20180130_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatas',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='create_date',
            field=models.DateField(null=True),
        ),
    ]
