# Generated by Django 2.0.1 on 2018-01-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycreditcard', '0003_auto_20180130_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdatas',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accountdatas',
            name='region',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
