# Generated by Django 2.0.1 on 2018-01-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycreditcard', '0004_auto_20180130_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatas',
            name='img',
            field=models.ImageField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
